version: '3'
services:

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://db_223306781sit722week8_user:93BolDF9UadupPfSFmEr4D4RqYL7styV@dpg-crcn7grv2p9s73cj4cv0-a.oregon-postgres.render.com/db_223306781sit722week8
    restart: "no"

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "4001:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://db_223306781sit722week8_user:93BolDF9UadupPfSFmEr4D4RqYL7styV@dpg-crcn7grv2p9s73cj4cv0-a.oregon-postgres.render.com/db_223306781sit722week8
    restart: "no"