# To deploy:
#
# kubectl apply -f scripts/deployment.yml
#

apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
     - name: book-catalog
       protocol: TCP
       port: 4001
       targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: 223306781sit722week802.azurecr.io/book-catalog:latest
        imagePullPolicy: IfNotPresent
        ports: 
          - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://db_223306781sit722week8_user:93BolDF9UadupPfSFmEr4D4RqYL7styV@dpg-crcn7grv2p9s73cj4cv0-a.oregon-postgres.render.com/db_223306781sit722week8"

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
     - name: inventory-management
       protocol: TCP
       port: 4000
       targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: 223306781sit722week802.azurecr.io/inventory-management:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://db_223306781sit722week8_user:93BolDF9UadupPfSFmEr4D4RqYL7styV@dpg-crcn7grv2p9s73cj4cv0-a.oregon-postgres.render.com/db_223306781sit722week8"


